url: http://www.angusafes.com

title: ANGUSAFES

keywords: ANGU SAFE

description: Anggun Safe Manufacturing Co., Ltd. was established in 2013, specialized in the safe manufacturing, processing and sales.

permalink: /products/:title.html

relative_permalinks: false

exclude:
  - README.md
  - style.css
